### ISSUE TITLE
(Not Required) TO-DO Improvements

### ISSUE THREAD

**Issue by indexxing** [StarManTheGamer/poly-newdocs#2]
- ~~Fill out MovePosition and MoveRotation method description for MeshParts~~
- Add event parameters
- ~~Add meta accent color somehow for embeds~~
- Improve search by adding a div to exclude certain notes from search (only some notes currently have it)
- ~~Fix "Inherits [class name]" links on GitHub Pages~~

someone else can do:
- ~~Add icons to navbar and footer on new homepage~~
- Add some theme similarities between the entire docs and the homepage
- Add "Home" to homepage somehow that links to new homepage

**Comment by ItsLuiggiYahoo** [comment]
I added the icons

**Comment by indexxing** [comment]
> I added the icons

The icons you added were not what I meant, sorry.
